services:
  - type: web
    name: yellowairlines
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_BUILD_CACHE
        value: true
      - key: DISABLE_CACHE
        value: true 