services:
  - type: web
    name: yellowairlines
    env: node
    plan: free
    buildCommand: |
      echo "執行緊急修復..."
      node scripts/render-build-override.js
      npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_BUILD_CACHE
        value: true
      - key: DISABLE_CACHE
        value: true 