services:
  - type: web
    name: yellowairlines
    env: node
    plan: free
    buildCommand: |
      echo "執行緊急修復..."
      node scripts/emergency-register-fix.js
      node scripts/render-build-override.js
      node scripts/render-env-setup.js
      node scripts/fix-register-page-tailwind.js
      npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_BUILD_CACHE
        value: true
      - key: DISABLE_CACHE
        value: true
      - key: MONGODB_URI
        value: mongodb+srv://yelluser:yell2024pass@cluster0.atvupvb.mongodb.net/yellairlines?retryWrites=true&w=majority
      - key: USE_MOCK_DB
        value: "false"
      - key: JWT_SECRET
        value: yellow_airlines_jwt_secret_key_2024 