services:
  - type: web
    name: yellow-airlines
    env: node
    buildCommand: npm ci && npm run fix-directory && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    plan: free 